<?php
/**
 * TL_ROOT/system/modules/linkslist/languages/nl/modules.php 
 * 
 * Contao extension: linkslist 1.1.1 rc1 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2014 gfg-development 
 * License   : LGPL 
 * Author    : Gerrit Grutzeck (gfg-development), http://www.gfg-development.de 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['linkslist']['0'] = "Linklijst";
$GLOBALS['TL_LANG']['MOD']['linkslist']['1'] = "Bewerk linklijst";
$GLOBALS['TL_LANG']['FMD']['linkslist'] = "Linklijst";
$GLOBALS['TL_LANG']['FMD']['linkslist_list']['0'] = "Linklijst";
$GLOBALS['TL_LANG']['FMD']['linkslist_list']['1'] = "Voegt een linklijst toe aan de pagina";
$GLOBALS['TL_LANG']['tl_module']['sort_legend'] = "Sorteer";
$GLOBALS['TL_LANG']['tl_module']['config_legend'] = "Module configuratie";
$GLOBALS['TL_LANG']['tl_module']['linkslist_sorting']['0'] = "Wijze van sorteren";
$GLOBALS['TL_LANG']['tl_module']['linkslist_sorting']['1'] = "Kies wijze van sorteren";
$GLOBALS['TL_LANG']['tl_module']['linkslist_sortings']['A'] = "alfabetisch (naam)";
$GLOBALS['TL_LANG']['tl_module']['linkslist_sortings']['B'] = "alfabetisch (URL)";
$GLOBALS['TL_LANG']['tl_module']['linkslist_sortings']['C'] = "datum oplopend";
$GLOBALS['TL_LANG']['tl_module']['linkslist_sortings']['D'] = "datum aflopend";
$GLOBALS['TL_LANG']['tl_module']['linkslist_use_subtitles']['0'] = "Toon namen van linklijsten in frontend";
$GLOBALS['TL_LANG']['tl_module']['linkslist_use_subtitles']['1'] = "De namen van de linklijsten worden getoond als tussenkoppen.";
$GLOBALS['TL_LANG']['tl_module']['linkslist_id']['0'] = "Linklijsten";
$GLOBALS['TL_LANG']['tl_module']['linkslist_id']['1'] = "Kies een of meer linklijsten.";
 
?>
