<?php
/**
 * TL_ROOT/system/modules/linkslist/languages/nl/tl_linkslist_list.php 
 * 
 * Contao extension: linkslist 1.1.1 rc1 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2014 gfg-development 
 * License   : LGPL 
 * Author    : Gerrit Grutzeck (gfg-development), http://www.gfg-development.de 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_linkslist_list']['title_legend'] = "Titel";
$GLOBALS['TL_LANG']['tl_linkslist_list']['name']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_linkslist_list']['name']['1'] = "Geef titel van de linklijst";
$GLOBALS['TL_LANG']['tl_linkslist_list']['new']['0'] = "Nieuwe linklijst";
$GLOBALS['TL_LANG']['tl_linkslist_list']['new']['1'] = "Maak een nieuwe linklijst.";
$GLOBALS['TL_LANG']['tl_linkslist_list']['edit']['0'] = "Bewerk linklijst";
$GLOBALS['TL_LANG']['tl_linkslist_list']['edit']['1'] = "Bewerk linklijst ID %s";
$GLOBALS['TL_LANG']['tl_linkslist_list']['delete']['0'] = "Wis linklijst";
$GLOBALS['TL_LANG']['tl_linkslist_list']['delete']['1'] = "Wis linklijst ID %s";
$GLOBALS['TL_LANG']['tl_linkslist_list']['show']['0'] = "Details linklijst";
$GLOBALS['TL_LANG']['tl_linkslist_list']['show']['1'] = "Toon details linklijst ID %s";
 
?>
