<?php
/**
 * TL_ROOT/system/modules/linkslist/languages/nl/tl_linkslist_link.php 
 * 
 * Contao extension: linkslist 1.1.1 rc1 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2014 gfg-development 
 * License   : LGPL 
 * Author    : Gerrit Grutzeck (gfg-development), http://www.gfg-development.de 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_linkslist_link']['title_legend'] = "Titel";
$GLOBALS['TL_LANG']['tl_linkslist_link']['link_legend'] = "Link";
$GLOBALS['TL_LANG']['tl_linkslist_link']['name']['0'] = "Naam";
$GLOBALS['TL_LANG']['tl_linkslist_link']['name']['1'] = "Geef naam van de link.";
$GLOBALS['TL_LANG']['tl_linkslist_link']['url']['0'] = "URL";
$GLOBALS['TL_LANG']['tl_linkslist_link']['url']['1'] = "Geef de URL, inclusief http://.";
$GLOBALS['TL_LANG']['tl_linkslist_link']['description']['0'] = "Beschrijving";
$GLOBALS['TL_LANG']['tl_linkslist_link']['description']['1'] = "Geef een beschrijving van de link.";
$GLOBALS['TL_LANG']['tl_linkslist_link']['info']['0'] = "Informatie";
$GLOBALS['TL_LANG']['tl_linkslist_link']['info']['1'] = "Extra informatie over de link.";
$GLOBALS['TL_LANG']['tl_linkslist_link']['new']['0'] = "Nieuwe link";
$GLOBALS['TL_LANG']['tl_linkslist_link']['new']['1'] = "Maak een nieuwe link.";
$GLOBALS['TL_LANG']['tl_linkslist_link']['edit']['0'] = "Bewerk link";
$GLOBALS['TL_LANG']['tl_linkslist_link']['edit']['1'] = "Bewerk link ID %s";
$GLOBALS['TL_LANG']['tl_linkslist_link']['delete']['0'] = "Wis link";
$GLOBALS['TL_LANG']['tl_linkslist_link']['delete']['1'] = "Wis link ID %s";
$GLOBALS['TL_LANG']['tl_linkslist_link']['show']['0'] = "Link details";
$GLOBALS['TL_LANG']['tl_linkslist_link']['show']['1'] = "Toon details link ID %s";
$GLOBALS['TL_LANG']['tl_linkslist_link']['file']['0'] = "Bestand";
$GLOBALS['TL_LANG']['tl_linkslist_link']['file']['1'] = "Kies het bestand waarheen de link verwijst.";
$GLOBALS['TL_LANG']['tl_linkslist_link']['page']['0'] = "Lokale pagina";
$GLOBALS['TL_LANG']['tl_linkslist_link']['page']['1'] = "Kies de lokale pagina waarheen de link verwijst.";
$GLOBALS['TL_LANG']['tl_linkslist_link']['target']['0'] = "Open link in nieuw venster/tab";
$GLOBALS['TL_LANG']['tl_linkslist_link']['target']['1'] = "De link kan wel/niet geopend worden in een nieuw venster of een nieuwe tab. Let op: deze optie negeert de instelling van de linklijst.";
$GLOBALS['TL_LANG']['tl_linkslist_link']['linksource']['0'] = "Doel van de link";
$GLOBALS['TL_LANG']['tl_linkslist_link']['linksource']['1'] = "Kies het doel van de link.";
$GLOBALS['TL_LANG']['tl_linkslist_link']['linksources']['external'] = "Extern";
$GLOBALS['TL_LANG']['tl_linkslist_link']['linksources']['local'] = "Lokaal";
$GLOBALS['TL_LANG']['tl_linkslist_link']['linksources']['page'] = "Lokale pagina";
$GLOBALS['TL_LANG']['tl_linkslist_link']['targets']['self'] = "Blijf in venster/tab";
$GLOBALS['TL_LANG']['tl_linkslist_link']['targets']['blank'] = "Nieuw venster / nieuwe tab";
 
?>
