<?php
/**
 * TL_ROOT/system/modules/linkslist/languages/nl/modules.php
 *
 * Contao extension: linkslist 1.1.1 rc1
 * Dutch translation file
 *
 * Copyright : &copy; 2014 gfg-development
 * License   : LGPL
 * Author    : Gerrit Grutzeck (gfg-development), http://www.gfg-development.de
 * Translator: Just Schimmelpenninck (justs)
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['CTE']['linkslist_list'][0] = "Linklijst";
$GLOBALS['TL_LANG']['CTE']['linkslist_list'][1] = "Bewerk linklijst";

$GLOBALS['TL_LANG']['tl_content']['sort_legend'] = "Sorteer";
$GLOBALS['TL_LANG']['tl_content']['config_legend'] = "configuratie";
$GLOBALS['TL_LANG']['tl_content']['linkslist_sorting']['0'] = "Wijze van sorteren";
$GLOBALS['TL_LANG']['tl_content']['linkslist_sorting']['1'] = "Kies wijze van sorteren";
$GLOBALS['TL_LANG']['tl_content']['linkslist_sortings']['A'] = "alfabetisch (naam)";
$GLOBALS['TL_LANG']['tl_content']['linkslist_sortings']['B'] = "alfabetisch (URL)";
$GLOBALS['TL_LANG']['tl_content']['linkslist_sortings']['C'] = "datum oplopend";
$GLOBALS['TL_LANG']['tl_content']['linkslist_sortings']['D'] = "datum aflopend";
$GLOBALS['TL_LANG']['tl_content']['linkslist_use_subtitles']['0'] = "Toon namen van linklijsten in frontend";
$GLOBALS['TL_LANG']['tl_content']['linkslist_use_subtitles']['1'] = "De namen van de linklijsten worden getoond als tussenkoppen.";
$GLOBALS['TL_LANG']['tl_content']['linkslist_id']['0'] = "Linklijsten";
$GLOBALS['TL_LANG']['tl_content']['linkslist_id']['1'] = "Kies een of meer linklijsten.";

?>
